name: bonsoir
description: A Zeroconf library that allows you to discover network services and to broadcast your own. Based on Apple Bonjour and Android NSD.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 5.1.1
publish_to: none
funding:
 - https://ko-fi.com/Skyost
 - https://paypal.me/Skyost
screenshots:
  - description: 'Bonsoir preview.'
    path: images/preview.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: 
    path: ../bonsoir_platform_interface/
  bonsoir_android:
    path: ../bonsoir_android/
  bonsoir_darwin:
    path: ../bonsoir_darwin/
  bonsoir_windows:
    path: ../bonsoir_windows/

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: bonsoir_android
      ios:
        default_package: bonsoir_darwin
      macos:
        default_package: bonsoir_darwin
      windows:
        default_package: bonsoir_windows
