name: bonsoir_darwin
description: Darwin (iOS & macOS) implementation of the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_darwin
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 5.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      ios:
        pluginClass: SwiftBonsoirPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: SwiftBonsoirPlugin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/

dependency_overrides:
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/
